### ISSUE TITLE
Product without attributes causes warning

### ISSUE THREAD

**Issue by nattywebdev** [backdrop-contrib/uc_attribute_views#3]
When I edit a product (without attributes) or add it to the cart, I see this warning message:

``Warning: Invalid argument supplied for foreach() in UcAttributesViewsAttributesField->pre_render() (line 26 of /app/web/modules/uc_attribute_views/views/UcAttributesViewsAttributesField.php).``

I'm not sure what this means, or whether it is important.

When a product has attributes, this is not displayed.

Can you advise please?

**Comment by argiepiano** [comment]
@nattywebdev thanks for reporting. I believe my PR fixes this. Can you please patch the module and test the fix? If it works for you, then I'll merge and do a new release.

**Comment by nattywebdev** [comment]
@argiepiano thank you so much - yes I can confirm that the change to `uc_attribute_views/views/UcAttributesViewsAttributesField.php`
has stopped the warning messages.

Thank you - much appreciated!

**Comment by argiepiano** [comment]
Great. Merging
